import { COLORS } from '@@constants/colors';
import { SERVICE_STATUS } from '@@stores/service/constants';

export const SERVICE_STATUS_STRINGS = {
  [SERVICE_STATUS.IDLE]: '',
  [SERVICE_STATUS.REQUESTED_OFFER]: '제안 요청',
  [SERVICE_STATUS.CANCELED_OFFER]: '제안 취소',
  [SERVICE_STATUS.PENDING]: '구인 진행 중',
  [SERVICE_STATUS.MATCHED]: '매칭 완료',
  [SERVICE_STATUS.REJECTED]: '매칭 취소',
} as const;

export const SERVICE_STATUS_BACKGROND = {
  [SERVICE_STATUS.IDLE]: COLORS.GRAY_SCALE_000,
  [SERVICE_STATUS.REQUESTED_OFFER]: COLORS.MAIN_050,
  [SERVICE_STATUS.CANCELED_OFFER]: COLORS.GRAY_SCALE_050,
  [SERVICE_STATUS.PENDING]: COLORS.MAIN_050,
  [SERVICE_STATUS.MATCHED]: COLORS.MAIN_050,
  [SERVICE_STATUS.REJECTED]: COLORS.GRAY_SCALE_050,
} as const;

export const SERVICE_STATUS_COLOR = {
  [SERVICE_STATUS.IDLE]: COLORS.GRAY_SCALE_000,
  [SERVICE_STATUS.REQUESTED_OFFER]: COLORS.MAIN_700,
  [SERVICE_STATUS.CANCELED_OFFER]: COLORS.GRAY_SCALE_700,
  [SERVICE_STATUS.PENDING]: COLORS.MAIN_700,
  [SERVICE_STATUS.MATCHED]: COLORS.MAIN_700,
  [SERVICE_STATUS.REJECTED]: COLORS.GRAY_SCALE_700,
} as const;
